name: PR Scripts

on: [push, pull_request]
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: View context attributes
      uses: actions/github-script@v5
      with:
        script: console.log(context)

