name: PR Scripts

on: [push, pull_request]
  # pull_request:
  #   types:
  #     - opened
  #     - edited

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
      - uses: actions/checkout@v2
        with:
          script: |
          if(context.payload.pull_request.title == "" || context.payload.pull_request.description == ""){
            core.setFailed('Description or title are null!')
          }

          console.log(context)

