name: pr

on: 
  pull_request:
    types: [opened,edited,synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v5
      env:
        SHA: '${{env.parentSHA}}'
      with:
        script: |
          const script = require('./.github/workflows/script.js')
          async script({github, context})